
// Get user
GET https://script.google.com/macros/s/AKfycbwOnPeGXIUEpHiilWekOKvX1DhDGZBiWB5cVzjTSsGj2nDKHI__jBNg7Kdb0V6kTitf/exec?action=getUsers&top=20&username=

###

GET https://script.google.com/macros/s/AKfycbwOnPeGXIUEpHiilWekOKvX1DhDGZBiWB5cVzjTSsGj2nDKHI__jBNg7Kdb0V6kTitf/exec?action=getUsers&top=20&username=